name: Daily Discord Notification

on:
  schedule:
    - cron: "0 12 * * *"  # Executa diariamente às 9h de Brasília (12h UTC)
  workflow_dispatch:

jobs:
  send-discord-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          node-version: '20'  # Usa Node.js 20

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          node-version: '20'  # Usa Node.js 20

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py python-dotenv

      - name: Run Discord notification script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: |
          python send_discord_message.py
